config/routes.rb
Rails.application.routes.draw do
  resources :advices
  resources :comments
  resources :offers
  resources :requests
  resources :questions
  resources :categories
  devise_for :admins, path: 'admin' #, controllers: { sessions: "admins/sessions"}
  devise_for :lawyers, path: 'lawyer' #, controllers: { sessions: "lawyers/sessions"}
  devise_for :clients, path: 'client' #, controllers: { sessions: "clients/sessions"}
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'public#index'
  resources :lawyers, only: [:index]
  resources :searches
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :bigint           not null, primary key
#  body        :text
#  solved      :boolean          default(FALSE)
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#  client_id   :bigint           not null
#
# Indexes
#
#  index_questions_on_category_id  (category_id)
#  index_questions_on_client_id    (client_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (client_id => clients.id)
#
class Question < ApplicationRecord
  belongs_to :category
  belongs_to :client
  has_many :comments
  has_many :advices
  has_rich_text :content
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :authenticate_client!, only: %i[ new create edit update destroy ]

  # GET /questions or /questions.json
  def index
    
    @questions = Question.includes(:categories, :clients, :comments, :lawyers)
  end

  # GET /questions/1 or /questions/1.json
  def show
    set_question
    @comment = Comment.new
    @advice = Advice.new
    @advices = Advice.includes(:lawyer)
    @comments = Comment.includes(:client)
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.includes(:client, :comments, :advices).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:title, :body, :category_id, :client_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_advices.html.erb
<% advices.each do |advice|%>
<div class="card mb-3">
  <div class="card-header bg-warning">
    <%= advice.lawyer.first_name %>
  </div>
  <div class="card-body">
    <%= advice.message.html_safe %>
  </div>
</div>

<div class="mb-3">
  <%= render "questions/comments", comments: advice.comments%>
</div>

<% end %>

app/views/questions/_comments.html.erb
<% comments.each do |comment|%>
<div class="card mb-3">
  <div class="card-header" style="background-color: #efe5d9;">
    <%= 'เจ้าของคำถาม' %>
  </div>
  <div class="card-body">
    <%= comment.message.html_safe %>
  </div>
</div>
<% end %>

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, prompt: "Choose a Company" %>
    <%= f.rich_text_area :body %>
    <%= f.association :category, label_method: :subject %>
    <%= f.association :client, :as => :hidden, :input_html => { :value => current_client.id }  %>  
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/questions/_list.html.erb
  <% @questions.each do |question|%>
  <div class="row">
    <div class="col-12">
      <div class="card mb-3">
        <div class="card-header">
          <%= link_to question.title, question_path(question.id), class: "text-xl mb-1" %>
          <div>
          <small class="font-weight-bold ml-auto"> ตั้งโดย 
          <% if question.client.nickname%>
          <%= question.client.nickname %>
          <%else%>
          ผู้ใช้ที่ไม่มีชื่อ
          <%end%>
          เมื่อ <%= question.created_at %> </small>
        </div>
        </div>
        <div class="card-body">
          <p class="card-text"><%= truncate question.body.html_safe, length: 200 %></p>
        </div>
      </div>
    </div>
    
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Category</th>
      <th>Clients</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.body %></td>
        <td><%= question.category.name %></td>
        <td><%= question.client_id %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-12">
    <div class="card mb-3">
      <div class="card-header font-weight-bold" style="background-color: #efe5d9;">
        <%= @question.title %>
      </div>
      <div class="card-body">
        <%= @question.body.html_safe %>
      </div>
    </div>
  </div>
</div>


<div class="mb-3">
  <%= render "questions/advices", advices: @advices%>
</div>

<% if client_signed_in? && @question.client.id == current_client.id %>
<%= form_for @comment, remote: true do |form|%>
  <%= form.hidden_field :question_id, value: @question.id%>
  <%= form.hidden_field :client_id, value: @question.client.id%>
  <%= form.hidden_field :advice_id, value: @question.advice.id%>
  <div class="card mb-3">
    <div class="card-header">
      <%= form.label :message, "ความคิดเห็น" %>
    </div>
    <div class="card-body">
      <%= form.rich_text_area :message, class: "form-control"%>
    </div>
    <div class="card-footer">
      <%= form.submit "ส่งความคิดเห็น", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<% end %>

<% if lawyer_signed_in? %>
<%= form_for @advice, remote: true do |form|%>
  <%= form.hidden_field :question_id, value: @question.id%>
  <%= form.hidden_field :lawyer_id, value: current_lawyer.id%>
  <div class="card mb-3">
    <div class="card-header">
      <%= form.label :message, "ความคิดเห็น" %>
    </div>
    <div class="card-body">
      <%= form.rich_text_area :message, class: "form-control"%>
    </div>
    <div class="card-footer">
      <%= form.submit "ส่งความคิดเห็น", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<% end %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>